### ISSUE TITLE
GetDeviceManagementInfo slow... then "Killed"

### ISSUE THREAD

**Issue by Nabla128k** [diraimondo/gmusicproxy#100]
Hi, I'm testing GMusicProxy on my Debian server and running in this:

`[INFO] (GMusicProxy:980): Google Play Music Proxy 1.0.9b2 (© Mario Di Raimondo)

[DEBUG] (GMusicProxy:1001): configuration used:
{'bind_address': '0.0.0.0',
 'config': <open file '/usr/share/gmusicproxy/gmusicproxy.cfg', mode 'r' at 0x3314ed0>,
 'daemon': False,
 'debug': True,
 'device_id': 'xxxx',
 'disable_all_access': False,
 'disable_playcount_increment': False,
 'disable_version_check': True,
 'email': 'xxx',
 'extended_m3u': False,
 'host': '**auto**',
 'keyring_backend': None,
 'keyring_entry': None,
 'keyring_service': None,
 'list_devices': False,
 'list_keyring_backends': False,
 'log': 'log.log',
 'password': '***OMITTED***',
 'port': 9999,
 'shoutcast_metadata': False}

[DEBUG] (shared:202): GetDeviceManagementInfo(args=[], kwargs={})
[DEBUG] (shared:243): {u'kind': u'sj#userClientIdList', u'data': {u'items': [{u'friendlyName': u'Google Play Music for Chrome on Windows', ...
[INFO] (mobileclient:144): authenticated
[DEBUG] (shared:202): Config(args=[], kwargs={})
[DEBUG] (shared:243): {u'kind': u'sj#configList', u'data': {u'entries': ....
[INFO] (mobileclient:149): subscribed
[INFO] (GMusicProxy:1035): Pre-fetching list of songs in collection
[DEBUG] (shared:202): ListTracks(args=[], kwargs={'start_token': None, u'max_results': 20000})
Killed`

After GetDeviceManagementInfo it takes quite long time (20-40 seconds) to continue...

The same configuration (cfg file) works well on my windows machine running the same verison of GMusicProxy...

Any idea?

**Comment by diraimondo** [comment]
It could be a network issue (for example, a slow DNS request handling). You could add some `logger.debug(...)` instructions after line 1001 to spot the blocking step.

**Comment by diraimondo** [comment]
Is the problem this there? Did you debug it?

**Comment by diraimondo** [comment]
I'm going to close the report for lack of feedback. Feel free to re-open it if the problem is still there.
