### ISSUE TITLE
authentication - I am not even seeing a report from google showing a failed attempt

### ISSUE THREAD

**Issue by nulesus** [diraimondo/gmusicproxy#102]
https://github.com/diraimondo/gmusicproxy.git

**Comment by diraimondo** [comment]
I guess this is the first report in your life...
You should add more details and log. Has GMusicProxy ever authenticated for you? Does it stop to work after a working period? What credentials do you use: main password or an application specific one?

I'm not aware of any "failed authentication attempt" report created using GMusic API.
