### ISSUE TITLE
Installation error: "netifaces.c:1:20: fatal error: Python.h: No such file or directory"

### ISSUE THREAD

**Issue by User2020** [diraimondo/gmusicproxy#20]
Hi.  Please forgive me if I am doing this wrong... this is my first GitHub entry.

I was so excited to see your work.  Thank you for sharing it.  But I am having an issue installing it on my Pi.  I am running Raspian and it is pretty much a fresh install.  Things were going well for awhile until I hit the following (including as much info as possible for you - see the end for the error).

Please let me know if I can provide any more info or if I should go about this a different way.  Noob here but picking things up fast  :)  Thanks a lot.

(I followed the directions exactly.  I also tried the steps under "The right way to use an under-development python project makes use of virtualenv and virtualenvwrapper utilities" but got the same error during setup.)
# 

sudo pip install https://github.com/diraimondo/gmusicproxy/tarball/master

Downloading/unpacking https://github.com/diraimondo/gmusicproxy/tarball/master
  Downloading master (unknown size): 25Kb downloaded
  Running setup.py egg_info for package from https://github.com/diraimondo/gmusi     cproxy/tarball/master

Downloading/unpacking gmusicapi>=4.0.0 (from gmusicproxy==0.9.8)
  Downloading gmusicapi-4.0.0.tar.gz (144Kb): 144Kb downloaded
  Running setup.py egg_info for package gmusicapi

```
warning: no previously-included files matching '_local_*.py' found anywhere      in distribution
```

Downloading/unpacking netifaces (from gmusicproxy==0.9.8)
  Downloading netifaces-0.10.4.tar.gz
  Running setup.py egg_info for package netifaces

Downloading/unpacking pyxdg (from gmusicproxy==0.9.8)
  Downloading pyxdg-0.25.tar.gz (48Kb): 48Kb downloaded
  Running setup.py egg_info for package pyxdg

Downloading/unpacking eyed3 (from gmusicproxy==0.9.8)
  Downloading eyeD3-0.7.5.tgz (221Kb): 221Kb downloaded
  Running setup.py egg_info for package eyed3
    warning: no previously-included files matching '*' found under directory 'do     cs/_build'
Downloading/unpacking python-daemon (from gmusicproxy==0.9.8)
  Downloading python-daemon-1.6.1.tar.gz (47Kb): 47Kb downloaded
  Running setup.py egg_info for package python-daemon

Downloading/unpacking validictory>=0.8.0,!=0.9.2 (from gmusicapi>=4.0.0->gmusicp     roxy==0.9.8)
  Downloading validictory-1.0.0a2.tar.gz
  Running setup.py egg_info for package validictory

```
warning: no files found matching 'CHANGELOG.txt'
```

Downloading/unpacking decorator>=3.3.1 (from gmusicapi>=4.0.0->gmusicproxy==0.9.     8)
  Downloading decorator-3.4.0.tar.gz
  Running setup.py egg_info for package decorator

```
warning: no previously-included files found matching 'Makefile'
```

Downloading/unpacking mutagen>=1.18 (from gmusicapi>=4.0.0->gmusicproxy==0.9.8)
  Downloading mutagen-1.26.tar.gz (868Kb): 868Kb downloaded
  Running setup.py egg_info for package mutagen

Downloading/unpacking protobuf>=2.4.1 (from gmusicapi>=4.0.0->gmusicproxy==0.9.8     )
  Downloading protobuf-2.6.1.tar.gz (188Kb): 188Kb downloaded
  Running setup.py egg_info for package protobuf

```
Installed /home/pi/build/protobuf/google_apputils-0.4.1-py2.7.egg
Searching for pytz>=2010
Reading http://pypi.python.org/simple/pytz/
Best match: pytz 2014.9
Downloading https://pypi.python.org/packages/2.7/p/pytz/pytz-2014.9-py2.7.eg     g#md5=b8149d1f94d12b402ac6e27a7b12353b
Processing pytz-2014.9-py2.7.egg
Extracting pytz-2014.9-py2.7.egg to /home/pi/build/protobuf

Installed /home/pi/build/protobuf/pytz-2014.9-py2.7.egg
Searching for python-gflags>=1.4
Reading http://pypi.python.org/simple/python-gflags/
Reading http://code.google.com/p/python-gflags
Best match: python-gflags 2.0
Downloading https://pypi.python.org/packages/source/p/python-gflags/python-g     flags-2.0.tar.gz#md5=23c9a793959a54971b1f094b0c6d03b1
Processing python-gflags-2.0.tar.gz
Running python-gflags-2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install     -r0ozxA/python-gflags-2.0/egg-dist-tmp-QaJaQz
zip_safe flag not set; analyzing archive contents...

Installed /home/pi/build/protobuf/python_gflags-2.0-py2.7.egg
Searching for python-dateutil>=1.4
Reading http://pypi.python.org/simple/python-dateutil/
Reading http://labix.org/python-dateutil
Best match: python-dateutil 2.2
Downloading https://pypi.python.org/packages/source/p/python-dateutil/python     -dateutil-2.2.tar.gz#md5=c1f654d0ff7e33999380a8ba9783fd5c
Processing python-dateutil-2.2.tar.gz
Running python-dateutil-2.2/setup.py -q bdist_egg --dist-dir /tmp/easy_insta     ll-PpFMva/python-dateutil-2.2/egg-dist-tmp-Dkt3K7

Installed /home/pi/build/protobuf/python_dateutil-2.2-py2.7.egg
Searching for six
Reading http://pypi.python.org/simple/six/
Best match: six 1.8.0
Downloading https://pypi.python.org/packages/source/s/six/six-1.8.0.tar.gz#m     d5=1626eb24cc889110c38f7e786ec69885
Processing six-1.8.0.tar.gz
Running six-1.8.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-s1gi79/     six-1.8.0/egg-dist-tmp-m7OUkR
no previously-included directories found matching 'documentation/_build'
zip_safe flag not set; analyzing archive contents...
six: module references __path__

Installed /home/pi/build/protobuf/six-1.8.0-py2.7.egg
```

Downloading/unpacking requests>=1.1.0,!=1.2.0,!=2.2.1 (from gmusicapi>=4.0.0->gm     usicproxy==0.9.8)
  Downloading requests-2.4.3.tar.gz (438Kb): 438Kb downloaded
  Running setup.py egg_info for package requests

Downloading/unpacking python-dateutil>=1.3,!=2.0 (from gmusicapi>=4.0.0->gmusicp     roxy==0.9.8)
  Downloading python-dateutil-2.2.tar.gz (259Kb): 259Kb downloaded
  Running setup.py egg_info for package python-dateutil

Downloading/unpacking proboscis>=1.2.5.1 (from gmusicapi>=4.0.0->gmusicproxy==0.     9.8)
  Downloading proboscis-1.2.6.0.tar.gz
  Running setup.py egg_info for package proboscis

Downloading/unpacking oauth2client>=1.1 (from gmusicapi>=4.0.0->gmusicproxy==0.9     .8)
  Downloading oauth2client-1.4.1.tar.gz (44Kb): 44Kb downloaded
  Running setup.py egg_info for package oauth2client

Downloading/unpacking mock>=0.7.0 (from gmusicapi>=4.0.0->gmusicproxy==0.9.8)
  Downloading mock-1.0.1.tar.gz (818Kb): 818Kb downloaded
  Running setup.py egg_info for package mock

```
warning: no files found matching '*.png' under directory 'docs'
warning: no files found matching '*.css' under directory 'docs'
warning: no files found matching '*.html' under directory 'docs'
warning: no files found matching '*.js' under directory 'docs'
```

Downloading/unpacking appdirs>=1.1.0 (from gmusicapi>=4.0.0->gmusicproxy==0.9.8)
  Downloading appdirs-1.4.0.tar.gz
  Running setup.py egg_info for package appdirs

Downloading/unpacking python-magic (from eyed3->gmusicproxy==0.9.8)
  Downloading python-magic-0.4.6.tar.gz
  Running setup.py egg_info for package python-magic

Requirement already satisfied (use --upgrade to upgrade): distribute in /usr/lib     /python2.7/dist-packages (from python-daemon->gmusicproxy==0.9.8)
Downloading/unpacking lockfile>=0.9 (from python-daemon->gmusicproxy==0.9.8)
  Downloading lockfile-0.10.2.tar.gz
  Running setup.py egg_info for package lockfile

```
Installed /home/pi/build/lockfile/pbr-0.10.0-py2.7.egg
[pbr] Processing SOURCES.txt
warning: LocalManifestMaker: standard file '-c' not found

warning: no previously-included files found matching '.gitignore'
warning: no previously-included files found matching '.gitreview'
warning: no previously-included files matching '*.pyc' found anywhere in dis     tribution
```

Downloading/unpacking six (from python-dateutil>=1.3,!=2.0->gmusicapi>=4.0.0->gm     usicproxy==0.9.8)
  Downloading six-1.8.0.tar.gz
  Running setup.py egg_info for package six

```
no previously-included directories found matching 'documentation/_build'
```

Downloading/unpacking httplib2>=0.8 (from oauth2client>=1.1->gmusicapi>=4.0.0->g     musicproxy==0.9.8)
  Downloading httplib2-0.9.tar.gz (204Kb): 204Kb downloaded
  Running setup.py egg_info for package httplib2

Downloading/unpacking pyasn1==0.1.7 (from oauth2client>=1.1->gmusicapi>=4.0.0->g     musicproxy==0.9.8)
  Downloading pyasn1-0.1.7.tar.gz (68Kb): 68Kb downloaded
  Running setup.py egg_info for package pyasn1

Downloading/unpacking pyasn1-modules==0.0.5 (from oauth2client>=1.1->gmusicapi>=     4.0.0->gmusicproxy==0.9.8)
  Downloading pyasn1-modules-0.0.5.tar.gz
  Running setup.py egg_info for package pyasn1-modules

Downloading/unpacking rsa==3.1.4 (from oauth2client>=1.1->gmusicapi>=4.0.0->gmus     icproxy==0.9.8)
  Downloading rsa-3.1.4.tar.gz
  Running setup.py egg_info for package rsa

```
warning: no files found matching 'README'
```

Installing collected packages: gmusicapi, netifaces, pyxdg, eyed3, python-daemon     , gmusicproxy, validictory, decorator, mutagen, protobuf, requests, python-dateu     til, proboscis, oauth2client, mock, appdirs, python-magic, lockfile, six, httpli     b2, pyasn1, pyasn1-modules, rsa
  Running setup.py install for gmusicapi

```
warning: no previously-included files matching '_local_*.py' found anywhere      in distribution
```

  Running setup.py install for netifaces
    checking for getifaddrs...found.
    checking for getnameinfo...found.
    checking for optional header files...netash/ash.h netatalk/at.h netax25/ax25     .h neteconet/ec.h netipx/ipx.h netpacket/packet.h linux/irda.h linux/atm.h linux     /llc.h linux/tipc.h linux/dn.h.
    checking whether struct sockaddr has a length field...no.
    checking which sockaddr_xxx structs are defined...at ax25 in in6 ipx un ash      ec ll atmpvc atmsvc dn irda llc.
    checking for routing socket support...no.
    checking for sysctl(CTL_NET...) support...no.
    checking for netlink support...yes.
    will use netlink to read routing table
    building 'netifaces' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-pro     totypes -fPIC -DNETIFACES_VERSION=0.10.4 -DHAVE_GETIFADDRS=1 -DHAVE_GETNAMEINFO=     1 -DHAVE_NETASH_ASH_H=1 -DHAVE_NETATALK_AT_H=1 -DHAVE_NETAX25_AX25_H=1 -DHAVE_NE     TECONET_EC_H=1 -DHAVE_NETIPX_IPX_H=1 -DHAVE_NETPACKET_PACKET_H=1 -DHAVE_LINUX_IR     DA_H=1 -DHAVE_LINUX_ATM_H=1 -DHAVE_LINUX_LLC_H=1 -DHAVE_LINUX_TIPC_H=1 -DHAVE_LI     NUX_DN_H=1 -DHAVE_SOCKADDR_AT=1 -DHAVE_SOCKADDR_AX25=1 -DHAVE_SOCKADDR_IN=1 -DHA     VE_SOCKADDR_IN6=1 -DHAVE_SOCKADDR_IPX=1 -DHAVE_SOCKADDR_UN=1 -DHAVE_SOCKADDR_ASH     =1 -DHAVE_SOCKADDR_EC=1 -DHAVE_SOCKADDR_LL=1 -DHAVE_SOCKADDR_ATMPVC=1 -DHAVE_SOC     KADDR_ATMSVC=1 -DHAVE_SOCKADDR_DN=1 -DHAVE_SOCKADDR_IRDA=1 -DHAVE_SOCKADDR_LLC=1      -DHAVE_PF_NETLINK=1 -I/usr/include/python2.7 -c netifaces.c -o build/temp.linux     -armv6l-2.7/netifaces.o
    netifaces.c:1:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools;**file**=     '/home/pi/build/netifaces/setup.py';exec(compile(open(**file**).read().replace('     \r\n', '\n'), **file**, 'exec'))" install --single-version-externally-managed --     record /tmp/pip-qjitpo-record/install-record.txt:
    running install

running build

running build_ext

checking for getifaddrs...found.

checking for getnameinfo...found.

checking for optional header files...netash/ash.h netatalk/at.h netax25/ax25.h n     eteconet/ec.h netipx/ipx.h netpacket/packet.h linux/irda.h linux/atm.h linux/llc     .h linux/tipc.h linux/dn.h.

checking whether struct sockaddr has a length field...no.

checking which sockaddr_xxx structs are defined...at ax25 in in6 ipx un ash ec l     l atmpvc atmsvc dn irda llc.

checking for routing socket support...no.

checking for sysctl(CTL_NET...) support...no.

checking for netlink support...yes.

will use netlink to read routing table

building 'netifaces' extension

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototy     pes -fPIC -DNETIFACES_VERSION=0.10.4 -DHAVE_GETIFADDRS=1 -DHAVE_GETNAMEINFO=1 -D     HAVE_NETASH_ASH_H=1 -DHAVE_NETATALK_AT_H=1 -DHAVE_NETAX25_AX25_H=1 -DHAVE_NETECO     NET_EC_H=1 -DHAVE_NETIPX_IPX_H=1 -DHAVE_NETPACKET_PACKET_H=1 -DHAVE_LINUX_IRDA_H     =1 -DHAVE_LINUX_ATM_H=1 -DHAVE_LINUX_LLC_H=1 -DHAVE_LINUX_TIPC_H=1 -DHAVE_LINUX_     DN_H=1 -DHAVE_SOCKADDR_AT=1 -DHAVE_SOCKADDR_AX25=1 -DHAVE_SOCKADDR_IN=1 -DHAVE_S     OCKADDR_IN6=1 -DHAVE_SOCKADDR_IPX=1 -DHAVE_SOCKADDR_UN=1 -DHAVE_SOCKADDR_ASH=1 -     DHAVE_SOCKADDR_EC=1 -DHAVE_SOCKADDR_LL=1 -DHAVE_SOCKADDR_ATMPVC=1 -DHAVE_SOCKADD     R_ATMSVC=1 -DHAVE_SOCKADDR_DN=1 -DHAVE_SOCKADDR_IRDA=1 -DHAVE_SOCKADDR_LLC=1 -DH     AVE_PF_NETLINK=1 -I/usr/include/python2.7 -c netifaces.c -o build/temp.linux-arm     v6l-2.7/netifaces.o

netifaces.c:1:20: fatal error: Python.h: No such file or directory

compilation terminated.

error: command 'gcc' failed with exit status 1

---

Command /usr/bin/python -c "import setuptools;**file**='/home/pi/build/netifaces     /setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, '     exec'))" install --single-version-externally-managed --record /tmp/pip-qjitpo-re     cord/install-record.txt failed with error code 1 in /home/pi/build/netifaces
Storing complete log in /root/.pip/pip.log

**Comment by jeliasson** [comment]
To anyone else ending up here using Python 3.4, try ```bash
sudo apt-get install python3.4-dev```.

**Comment by diraimondo** [comment]
The whole gmusicproxy was designed to work only with python 2.7.

**Comment by tianxialinghu** [comment]
if your linux like centos, youn need to yum install python-devel
