### ISSUE TITLE
get_song - no title, artist and time

### ISSUE THREAD

**Issue by TobiasH87** [diraimondo/gmusicproxy#21]
When I add songs with "get_song" in my player (example: VLC) i see no title, artist and time, i see only the url.

When i add a playlist with "get_playlist" i see all information, ..... but when a song from playlist is play ("get_song" is used), the time is erased.

I think the proxy will not pass this information, can you improve it? (Because i need the time/songlength.)

Thanks :)

**Comment by diraimondo** [comment]
I'm going to close the report because there are not evidence that this is a gmusicproxy fault or an example of working streamed mp3 URL with the requested features.

Feel free to reopen if you got further information.
