### ISSUE TITLE
login() takes exactly 4 arguments, 3 given

### ISSUE THREAD

**Issue by jeremyrogers** [diraimondo/gmusicproxy#26]
When I try to run GMusicProxy, I get this error:

Google Play Music Proxy 0.9.8 (© Mario Di Raimondo)

Traceback (most recent call last):
  File "/usr/bin/GMusicProxy", line 636, in <module>
    api = loginGM(config['email'], config['password'])
  File "/usr/bin/GMusicProxy", line 545, in loginGM
    api.login(email, password)
TypeError: login() takes exactly 4 arguments (3 given)

I'm on Arch Linux if it helps.

**Comment by diraimondo** [comment]
What version of gmusicapi have you installed? Is it the current master in git repository? The current version of gmusicproxy supports only the latest official release of gmusicapi (4.0.0). If the next official release will change the login api, I will adjust the gmusicapi code. 

I've just tested a fresh install using ``pip install https://github.com/diraimondo/gmusicproxy/tarball/master`` and it continues to work for me.

**Comment by jeremyrogers** [comment]
Ah, for some reason, I have 5.0.0-devel installed. Thanks.

**Comment by diraimondo** [comment]
The day after the closure of this issue, I have to switch on the develop branch of gmusicapi. The old login looks broken now. See new pushes.
