### ISSUE TITLE
Sorry, those credentials weren't accepted

### ISSUE THREAD

**Issue by bhanderson** [diraimondo/gmusicproxy#27]
```
Google Play Music Proxy 0.9.8 (© Mario Di Raimondo)

configuration used:
{'config': None,
 'daemon': False,
 'debug': True,
 'device_id': None,
 'disable_all_access': False,
 'disable_version_check': False,
 'email': '***OMITTED***',
 'extended_m3u': False,
 'host': '**auto**',
 'list_devices': True,
 'log': None,
 'password': '***OMITTED***',
 'port': 9999}

ClientLogin(<omitted>)
failed to authenticate
Sorry, those credentials weren't accepted.
```
I'm typing in my email and password on the command line but getting this error

**Comment by diraimondo** [comment]
I can confirm the problem on my system using a application-specific password.
It is related to another bug report opened on gmusicapi: https://github.com/simon-weber/Unofficial-Google-Music-API/issues/338

**Comment by diraimondo** [comment]
I'm switching on develop branch of Simon's gmusicapi. Just pushed these changes:
  - fixed login problem using the devel branch (5.0.0-dev0) of gmusicapi (today not yet released)
  - changed the installation instructions using pip `requirements.txt` file: this permits the automatic deploy of gmusicapi from github
  - the functionality `--list-devices` is actually broken: keep a copy of you device ids!

Please, test a fresh install using the new installation procedure: `pip install -r requirements.txt` and ack.

**Comment by kmac** [comment]
Hi, jumping in. I've tested using a fresh virtualenv install and it's working again. Thanks.

Steps (I'm on archlinux): 

    virtualenv2 ~/.virtualenvs/gmusic
    source ~/.virtualenvs/gmusic/bin/activate
    cd ~/.virtualenvs
    mkdir github-checkouts && cd github-checkouts
    git clone https://github.com/diraimondo/gmusicproxy.git
    cd gmusicproxy
    pip install --allow-external eyed3 --allow-unverified eyed3 -r requirements.txt

**Comment by bhanderson** [comment]
Worked for me also, thanks!
