### ISSUE TITLE
The 'gmusicapi>=5.0.0-dev0' distribution was not found and is required by gmusicproxy

### ISSUE THREAD

**Issue by Mlmlte** [diraimondo/gmusicproxy#28]
Hi guys,

A few days ago, I had the 'Sorry, those credentials weren't accepted' issue (just like bhanderson here: https://github.com/diraimondo/gmusicproxy/issues/27), so I figured I should upgrade to the latest version of gmusicproxy.

I'm running it on Windows using Cygwin.

```
$ pip install --allow-external eyed3 --allow-unverified eyed3 -r requirements.txt --upgrade
[...]
Successfully installed gmusicapi-4.0.0 gmusicproxy-0.9.8
```

But now, whenever I try to start gmusicproxy, I get the following error:

```
$ gmusicproxy
Traceback (most recent call last):
  File "/usr/bin/gmusicproxy", line 4, in <module>
    __import__('pkg_resources').require('gmusicproxy==0.9.8')
  File "build/bdist.cygwin-2.0.2-x86_64/egg/pkg_resources/__init__.py", line 3074, in <module>
  File "build/bdist.cygwin-2.0.2-x86_64/egg/pkg_resources/__init__.py", line 3060, in _call_aside
  File "build/bdist.cygwin-2.0.2-x86_64/egg/pkg_resources/__init__.py", line 3087, in _initialize_master_working_set
  File "build/bdist.cygwin-2.0.2-x86_64/egg/pkg_resources/__init__.py", line 647, in _build_master
  File "build/bdist.cygwin-2.0.2-x86_64/egg/pkg_resources/__init__.py", line 660, in _build_from_requirements
  File "build/bdist.cygwin-2.0.2-x86_64/egg/pkg_resources/__init__.py", line 833, in resolve
pkg_resources.DistributionNotFound: The 'gmusicapi>=5.0.0-dev0' distribution was not found and is required by gmusicproxy
```

How do you guys manage to make it work?

EDIT: I'm able to start gmusicproxy if I remove  'gmusicapi>=5.0.0-dev0' from install_requires, but then I get this error:
```
$ gmusicproxy -e ****@gmail.com -p **** -d ****
Google Play Music Proxy 0.9.8 (© Mario Di Raimondo)

Traceback (most recent call last):
  File "/usr/bin/gmusicproxy", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/*****/gmusicproxy/GMusicProxy", line 636, in <module>
    api = loginGM(config['email'], config['password'])
  File "/home/*****/gmusicproxy/GMusicProxy", line 545, in loginGM
    api.login(email, password, config['device_id'])
TypeError: login() takes exactly 3 arguments (4 given)
```

**Comment by diraimondo** [comment]
It is nice to learn that someone is using my project on Windows!

Getting on the problem, latest changes require gmusicapi>=5.0.0-dev0 to work. I don't understand why you pip doesn't download the correct version of gmusicapi: it continues to download version 4.0.0.
What version of pip are you using (`pip -V`)?

As a workaround you could manually install the correct version of gmusicapi using: 
`pip install git+https://github.com/simon-weber/Unofficial-Google-Music-API.git`

**Comment by Mlmlte** [comment]
And it has always been working like a charm on Windows :D

It seems like there was an issue with my version of pip, indeed.
I reinstalled it and used your workaround first, and it ended up working like a charm!

I have noticed something unusual though, some InsecureRequestWarning after start, see:
```
$ gmusicproxy --debug
Google Play Music Proxy 0.9.9 (© Mario Di Raimondo)

configuration used:
{'config': None,
 'daemon': False,
 'debug': True,
 'device_id': '*****',
 'disable_all_access': False,
 'disable_version_check': False,
 'email': '*****@gmail.com',
 'extended_m3u': False,
 'host': '**auto**',
 'list_devices': False,
 'log': None,
 'password': '***OMITTED***',
 'port': 9999}

/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
authenticated
Fetching lastest version of gmusicproxy...
latest available version: 0.9.9
installed version: 0.9.9
Listening on port 9999...
```

Thanks a lot for your great work and support, gmusicproxy rocks!

**Comment by TobiasH87** [comment]
Hello,

i have this problem on Debian 7 (Raspberry Pi 2).

I have use the easiest way for install and my password is a app-password.
And then i have use the workaround (sudo pip install git+https://github.com/simon-weber/Unofficial-Google-Music-API.git), but don't work. 

Some Ideas?

```$ GMusicProxy --email *******@gmail.com --password *********** --device-id *********** --debug
Google Play Music Proxy 1.0.0 (© Mario Di Raimondo)

configuration used:
{'config': None,
 'daemon': False,
 'debug': True,
 'device_id': '***********',
 'disable_all_access': False,
 'disable_version_check': False,
 'email': '*******@gmail.com',
 'extended_m3u': False,
 'host': '**auto**',
 'list_devices': False,
 'log': None,
 'password': '***OMITTED***',
 'port': 9999}

Traceback (most recent call last):
  File "/usr/local/bin/GMusicProxy", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/tobias/gmusicproxy/GMusicProxy", line 623, in <module>
    api = loginGM(config['email'], config['password'])
  File "/home/tobias/gmusicproxy/GMusicProxy", line 539, in loginGM
    api.login(email, password)
TypeError: login() takes exactly 4 arguments (3 given)```

My ip version:
$ pip --version
pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)

**Comment by diraimondo** [comment]
Now gmusicapi 5.0.0 is officially released. You have to install gmusicapi using `pip install gmusicapi`. Using the git repository you use the development version and now Simon has changed again the number of parameters...

**Comment by TobiasH87** [comment]
Thanks for your answer (and work), but what I try, it does't work. :(

I have use "pip install gmusicapi"....
Then i have uninstall gmusicapi and gmusicproxy and delete the folder in "/usr/local/lib/python2.7/dist-packages/". Download the zip files gmusicapi->5.0.0 and gmusicproxy-> 1.0.0. Then "sudo pip install -r requirements.txt" and "./setup.py" in gmusicapi and the same in gmusicproxy....

GMusicProxy --email **********@gmail.com --password ********** --device-id ********** --debug
Google Play Music Proxy 1.0.0 (© Mario Di Raimondo)

configuration used:
{'config': None,
 'daemon': False,
 'debug': True,
 'device_id': '**********',
 'disable_all_access': False,
 'disable_version_check': False,
 'email': '**********@gmail.com',
 'extended_m3u': False,
 'host': '**auto**',
 'list_devices': False,
 'log': None,
 'password': '***OMITTED***',
 'port': 9999}

Traceback (most recent call last):
  File "/usr/local/bin/GMusicProxy", line 4, in <module>
    __import__('pkg_resources').run_script('gmusicproxy==1.0.0', 'GMusicProxy')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/gmusicproxy-1.0.0-py2.7.egg/EGG-INFO/scripts/GMusicProxy", line 621, in <module>

  File "/usr/local/lib/python2.7/dist-packages/gmusicproxy-1.0.0-py2.7.egg/EGG-INFO/scripts/GMusicProxy", line 537, in loginGM

  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-5.0.0-py2.7.egg/gmusicapi/clients/mobileclient.py", line 39, in login
    if not self.session.login(email, password):
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-5.0.0-py2.7.egg/gmusicapi/session.py", line 162, in login
    res = gpsoauth.perform_master_login(email, password)
TypeError: perform_master_login() takes at least 3 arguments (2 given)


I think I'll just wait for the next version and then try again. Just i have no idea what I'm doing wrong. ^^

**Comment by TobiasH87** [comment]
Now i use temporary gmusicapi 4.0.0 and gmusicproxy 0.9.8 (ZIP installed) and it works :)

Thanks for the great work. :+1:

**Comment by 8leggedunicorn** [comment]
I'm not certain how the authors want to go about fixing this but I verified in the code that indeed these were changes made to the gpsoauth package 6 days ago see:

https://github.com/simon-weber/gpsoauth/commit/91acfd4e34075f0997bfaafa87c3d2088bb733e1

**Comment by diraimondo** [comment]
Just released a new version of gmusicproxy to use the new gmusicapi 6.0.0. Consider the idea of cleanup your installation and to start with fresh one.

**Comment by TobiasH87** [comment]
Thanks

gmusicproxy 1.0.1 and gmusicapi 6.0.0 works  :+1:

**Comment by kiai72** [comment]
@Mlmlte : hello, i tried to make this work on windows, but failed so far. Does it work for you on windows ? If so, will you please tell me, what python you are using (activephython ?). And can you please write down the step's you did ? you wrote something about a workaround...
