### ISSUE TITLE
list-devices not working

### ISSUE THREAD

**Issue by f4hy** [diraimondo/gmusicproxy#31]
Running `GMusicProxy -L` or `GMusicProxy --list-devices` gives me

    Google Play Music Proxy 0.9.9.2 (© Mario Di Raimondo)
    
    Please, specify the ID of an Android device registered in your Google account in the config file or on the command-line. Use the option '--list-devices=true' to auto-discover the IDs.

Using `--list-devices=true` like it indicates gives 

    GMusicProxy: error: argument -L/--list-devices: ignored explicit argument 'true'

Is there some error in argparse?

**Comment by diraimondo** [comment]
The second message is normal: it's not the way it is supposed to be used.

The first message doesn't make sense. Could you reply to few diagnostic questions and provide some information?
- what system do you use?
- did GMusicProxy worked for you in past on the same system?
- do you have a configuration file? If yes, what's the content?
- the output of `GMusicProxy --list-devices --debug`
- the output of `pip freeze`

**Comment by sucotronic** [comment]
I've suffered the same problem, and that's because the code forces you to put "something" as a device_id even when --list-devices is given. So, the workaround is:

    GMusicProxy -e sample@gmail.com -p "pass" -L -d 9

**Comment by diraimondo** [comment]
@sucotronic I don't understand the sense of this problem (and of the workaround). Could you argue. 

@f4hy If you don't provide further information, I have to close this report...

**Comment by f4hy** [comment]
Running with `GMusicProxy --list-devices --debug` I get

    Google Play Music Proxy 0.9.9.2 (© Mario Di Raimondo)
    
    configuration used:
    {'config': None,
     'daemon': False,
     'debug': True,
     'device_id': None,
     'disable_all_access': False,
     'disable_version_check': False,
     'email': '***CENSORED***',
     'extended_m3u': False,
     'host': '**auto**',
     'list_devices': True,
     'log': None,
     'password': '***OMITTED***',
     'port': 9999}
    
    Please, specify the ID of an Android device registered in your Google account in the config file or on the command-line. Use the option '--list-devices=true' to auto-discover the IDs.

So in the debug it does mark list_devices as True, but still asks me to specify the ID of an Android device.

If I do what @sucotronic suggests and provide a random false value for the device so pass `-L -d 12345` it works and proivdes me with the list of devices, so his workaround is good. 

Is the code checking if device_id is None before checking if list_devices is true?

**Comment by sucotronic** [comment]
@f4hy that's exactly what is happening :P
