### ISSUE TITLE
ImportError: cannot import name InsecureRequestWarning

### ISSUE THREAD

**Issue by TobiasH87** [diraimondo/gmusicproxy#35]
Hello,

i have my system (Raspberry Pi 2) reinstalled (Raspian Jessie / Debian 8 Jessie) and install the gmusicproxy like:
- git clone https://github.com/diraimondo/gmusicproxy.git
- sudo pip install -r requirements.txt
Now when i will start "GMusicProxy --config /home/pi/gmusicproxy.cfg" i become a error:

Traceback (most recent call last):
  File "/usr/local/bin/GMusicProxy", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/pi/gmusicproxy/GMusicProxy", line 29, in <module>
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
ImportError: cannot import name InsecureRequestWarning

What can i do or can you fix it? Thanks

I have seen, that gmusicapi 7.0.0 and gmusicproxy 1.0.2 is installed. I have in between attempts by the manual installation of gmusicproxy 1.0.1 and gmusicapi 6.0.0  to circumvent the problem, but unfortunately it has not helped. 
Here you can see all current package: http://pastebin.com/5y3USSk9

**Comment by diraimondo** [comment]
Is it installed the package `ca-certificates` in your system?

**Comment by TobiasH87** [comment]
Yes, is installed.

**Comment by diraimondo** [comment]
This looks related:
http://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue

Il giorno dom 4 ott 2015 21:14 Tobias Hargesheimer <notifications@github.com>
ha scritto:

**Comment by TobiasH87** [comment]
I found this to be the same time and have already edited my post (Edit2).

Thanks, for your work :-D
