### ISSUE TITLE
Track Data in ncmpcpp

### ISSUE THREAD

**Issue by nogz-zoned** [diraimondo/gmusicproxy#38]
Would it be possible, or is there some way, to get the track data into ncmpcpp?

**Comment by onespaceman** [comment]
You can use my script to add songs to mpd. It automatically imports track info.

https://github.com/onespaceman/gmpplay

**Comment by diraimondo** [comment]
Sorry for the late reply. I've never used ncmpcpp but I think you can use script like gmpplay or GMusic-MPD (see 'Related Projects' in README.md) to add tracks or create playlist with the proper URLs. After this, you manage the playback (play/stop/next/prev) with your preferred client.

I think this is not a proper issue report, so I'm going to close it. Feel free to reply on this report if you need further explanations.
