### ISSUE TITLE
Is "/search_id" not working ?

### ISSUE THREAD

**Issue by Drezzler** [diraimondo/gmusicproxy#39]
So , I am trying to used "/search_id" like so 

`curl -s 'http://localhost:9999/search_id?type=album&title=love'`

But no matter what i enter in the title param , i always get empty results , other queries such as 

`curl -s 'http://localhost:9999/get_album?id=B5sm5kgmtehbpzid7z6v74so6sq'`
Are working fine .

Thank you for this wonderfull tool and any help is really appreciated.

**Comment by diraimondo** [comment]
It's not a bug in the program but a bug in documentation: the default for the parameter `exact` for `search_id` is `yes`.  This means that to exactly search an album you have to provide the title AND the artist. For example: `curl -s 'http://localhost:9999/search_id?type=album&title=love%20story&artist=yelawolf'`
if you search with `exact=no`, the first matching album will be returned: `curl -s 'http://localhost:9999/search_id?type=album&title=love&exact=no'`

I will fix the documentation.
