### ISSUE TITLE
Exactly what I need, but how can I use this on Windows 10?

### ISSUE THREAD

**Issue by vovokrall** [diraimondo/gmusicproxy#42]
This is exactly what I need, play Google Music songs on VLC, but can someone help me to get it installed on Windows 10?

**Comment by diraimondo** [comment]
Sorry, I've never used (read as "I'm not interested in using") my software on platforms different than Linux. Some users reported that they were able to run it also on Windows (see issue #28).

**Comment by lukasbraach** [comment]
@vovokrall Just rent yourself a cheap linux vps (virtual private server) and install it there. But of corse you have to have basic linux skills. I can recommend [OVH](https://www.ovh.com/us/vps/vps-ssd.xml). Their cheapest vps costs just over 3 Euros
