### ISSUE TITLE
40 seconds to play a song?

### ISSUE THREAD

**Issue by calanor** [diraimondo/gmusicproxy#44]
Its normal 40s to get the stream of the song in get_song function?
With my old  0.8 version  the song is playing in 1 o 2 seconds.  

I noticed in debug mode that most of this time is getting the info of the song to add ID3tag of the stream.
Would it be possible to get the song without ID3tag (via option) in the case of the ID3tag is not needed?

(I'm runing GMusicProxy in a raspberry pi)

**Comment by diraimondo** [comment]
I used gmusicproxy on a RPi long time ago: it was slower than a regular PC but 40 seconds are abnormal for starting the stream of a song.
The ID3tag should be in use also in 0.8 release: it doesn't make sense to disable it for fix the problem. The tag is temporarily written to the disk (a constraint of the used lib). The used dirs should be, in sequence: /tmp, /var/tmp, and /usr/tmp. Is it possible that your RPi is using the sdcard for the /tmp/ dir? This could explain the slowness, more or less... Check the used filesystems with `mount`: the use of `tmpfs` for /tmp/ should speed-up this phase.

If this doesn't help, could you report a full debug log (copy&paste from the console), specifying the two lines, respectively, before and after the 40s stop?

**Comment by calanor** [comment]
Ok, are you right. Its not problem of get_track_info, the problem is that I use 
`disable_all_access': True, 
`
and the problem is in the line;

`137                      allSongs = self._robust_retry(lambda:api.get_all_songs())`

Here I I suppose can not do anything.

In my modified  0.8 version, I obtain the song info from a sqlite db prefilled with  api.get_all_songs().

Thanks.

**Comment by diraimondo** [comment]
Ok, I see the problem. This is a weird hack to the impossibility to use get_track_info without All Access service. This can be a performance problem with a big collection of uploaded songs.

See https://unofficial-google-music-api.readthedocs.org/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.get_track_info

As you proved, it could be possible to store the whole list in a sqlite database but we should manage its storage and update. Another idea could be to store a copy in RAM: it would be populated on startup and refetched upload look-up failure. Open to pull-request! ;-)

**Comment by diraimondo** [comment]
Ok, I'm working on the RAM-stored solution. I'll ask you to test it.

**Comment by calanor** [comment]
My hight-speed solution for testing has been make a global allSongs variable and move the function inside the main function after loginGM.
Work fine, but you need a more elegant solution.

**Comment by diraimondo** [comment]
Just pushed my solution: could you test it? It should pre-fetch the list on startup if AA is disabled. It is fetched on-request if you use uploaded mp3s (the uuid-style id are used). It is re-fetched if there is a look-up failure.

**Comment by diraimondo** [comment]
Just discovered that the slow-method was used (because necessary) also for the tracks in collection: the uuid-style ids where provided. We can't use get_track_info with these ids.
This means that also people with AA will enjoy this new feature.

**Comment by calanor** [comment]
Good Job.
Now it works fine.

I will add a hack that stored in a sqlite db allSongs info and I use this db for search song info and get art, duration,... Useful if you d'ont have AA.  Should ideally implement sqlite db (:memory) in GMusic proxy and use the current proxy queries for AA suscriptors.
