### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by nonoba** [diraimondo/gmusicproxy#47]
gmusicapi has added Python 3 support.

It would be nice to upgrade this to use it.

**Comment by diraimondo** [comment]
I know that gmusicapi now got the support for Python 3. I'm not in hurry to switch to the new version of the underlying language: this would not introduce any new function. 
In the new rewrite of the project I will consider the language switch.

As usual, specific Pull Requests are welcome.

I'll keep open this issue report as reminder. Thanks.

**Comment by diraimondo** [comment]
Please, test the new experimental support to Python 3. Let us know if it works for you.
