### ISSUE TITLE
403 Client Error: Forbidden

### ISSUE THREAD

**Issue by adamprato** [diraimondo/gmusicproxy#48]
Did a fresh pip install of required modules, started GMusicProxy without error. I can search for my songs, but I can't play any of my tracks. Here's an example

: arp_kiki/pts/28:0.30:~; GMusicProxy --extended-m3u --debug
Google Play Music Proxy 1.0.5 (© Mario Di Raimondo)

configuration used:
{'config': None,
 'daemon': False,
 'debug': True,
 'device_id': 'bf9a6221c0e00dc0',
 'disable_all_access': False,
 'disable_playcount_increment': False,
 'disable_version_check': False,
 'email': 'OMITTED@gmail.com',
 'extended_m3u': True,
 'host': '**auto**',
 'list_devices': False,
 'log': None,
 'password': '***OMITTED***',
 'port': 9999}

authenticated
Fetching lastest version of gmusicproxy...
latest available version: 1.0.4
installed version: 1.0.5
Pre-fetching list of songs in collection
_

When trying to use VLC to stream one of my uploaded songs:

request path: /get_song?id=9b1d1e62-4b83-3ec4-9db8-23a490bac444
Streaming song with id '9b1d1e62-4b83-3ec4-9db8-23a490bac444': Jason Green - god bless the child
{u'album': u'Jason Green',
 u'albumArtist': u'',
 u'artist': u'Jason Green',
 u'beatsPerMinute': 0,
 u'clientId': u'qnKrLx74JBqOxMfjSp5/GQ',
 u'comment': u'',
 u'composer': u'',
 u'creationTimestamp': u'1308372096694221',
 u'deleted': False,
 u'discNumber': 0,
 u'durationMillis': u'279000',
 u'estimatedSize': u'6773673',
 u'genre': u'Blues',
 u'id': u'9b1d1e62-4b83-3ec4-9db8-23a490bac444',
 u'kind': u'sj#track',
 u'lastModifiedTimestamp': u'1434481209008638',
 u'playCount': 0,
 u'rating': u'0',
 u'recentTimestamp': u'1308385312157000',
 u'title': u'god bless the child',
 u'totalDiscCount': 0,
 u'totalTrackCount': 14,
 u'trackNumber': 1,
 u'year': 2005}
GetStreamUrl(args=['9b1d1e62-4b83-3ec4-9db8-23a490bac444', '13806455504767028672', u'hi'], kwargs={})
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 33054)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/u/arp/gmusicproxy/GMusicProxy", line 471, in handle_one_request
    BaseHTTPServer.BaseHTTPRequestHandler.handle_one_request(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/u/arp/gmusicproxy/GMusicProxy", line 39, in do_GET
    self._get_song(id=params['id'][0])
  File "/u/arp/gmusicproxy/GMusicProxy", line 193, in _get_song
    url = self._robust_retry(lambda:api.get_stream_url(song_id=id))
  File "<decorator-gen-114>", line 2, in _robust_retry
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 390, in retry_wrapper
    return f(*args, **kwargs)
  File "/u/arp/gmusicproxy/GMusicProxy", line 467, in _robust_retry
    return func()
  File "/u/arp/gmusicproxy/GMusicProxy", line 193, in <lambda>
    url = self._robust_retry(lambda:api.get_stream_url(song_id=id))
  File "<decorator-gen-82>", line 2, in get_stream_url
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 296, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 275, in get_stream_url
    return self._make_call(mobileclient.GetStreamUrl, song_id, device_id, quality)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/shared.py", line 83, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 227, in perform
    raise CallFailure(err_msg, call_name)
CallFailure: GetStreamUrl: 403 Client Error: Forbidden
(requests kwargs: {u'url': u'https://android.clients.google.com/music/mplay', u'headers': {u'X-Device-ID': '13806455504767028672', u'Authorization': u'<omitted>'}, u'allow_redirects': False, u'params': {u'opt': u'hi', u'songid': '9b1d1e62-4b83-3ec4-9db8-23a490bac444', u'pt': u'e', u'slt': '1460091879532', u'sig': 'UTN1cr9kyTda6nqzrjoIXaqKL0A', u'net': u'mob'}, u'method': u'GET'})
(response was: '<HTML>\n<HEAD>\n<TITLE>Forbidden</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Forbidden</H1>\n<H2>Error 403</H2>\n</BODY>\n</HTML>\n')
----------------------------------------

I checked my authorized devices in google play and the host running gmusicapi is listed.

Any pointers for where to start looking?

**Comment by diraimondo** [comment]
I've just locally tested gmusicproxy with a track I uploaded in the past. It worked for me.

Does gmusicproxy work for you with the tracks of the store?
How do you get the id of the uploaded tracks? get_collection method?
Could you try a different device id? You can try to method to automatically generate a new one from your mac-address: leave the configuration unspecified.

**Comment by adamprato** [comment]
It was the device id. I thought I was supposed to generate one so I made a random one as long as the sample.

**Comment by diraimondo** [comment]
I'm happy you found the problem. Thank you for your kind donation.

**Comment by discipuloosho** [comment]
How can i change my device-id, please?
