### ISSUE TITLE
"year" not in id3 tags

### ISSUE THREAD

**Issue by adamprato** [diraimondo/gmusicproxy#49]
The eyeD3 tool has a -Y option which does:

>         if self.args.release_year is not None:
            # empty string means clean, None means not given
            year = self.args.release_year
            printWarning("Setting release year: %s" % year)
            tag.release_date = int(year) if year else None

Can you consider doing in _get_song():
>             if 'year' in info: tags.release_date = int(info['year'])

**Comment by adamprato** [comment]
Perhaps I should have tested first

>  244             if 'year' in info: tags.recording_date = int(info['year'])
 245             if 'year' in info: tags.release_date = int(info['year'])
 246             if 'year' in info: tags.original_release_date = int(info['year'])

None seem to add anything:

> 8 ID3 Frames:
TPOS (13 bytes)
TIT2 (29 bytes)
APIC (39247 bytes)
TRCK (13 bytes)
TPE2 (26 bytes)
TPE1 (26 bytes)
TALB (42 bytes)
TCON (18 bytes)
1024 bytes unused (padding)

I think that should have written TDAT/TRDA at least.

**Comment by diraimondo** [comment]
I'm not sure to understand your last post. Could you argue?

**Comment by adamprato** [comment]
I tried adding the year tag myself, and it didn't work. I'll close this out until I have an request that you can actually implement :)

**Comment by redlulz** [comment]
@adamprato your suggested changes work for me, so I added a pull request to this issue
