### ISSUE TITLE
API is blocking while search is playing one song

### ISSUE THREAD

**Issue by Luzifer** [diraimondo/gmusicproxy#53]
> As a user of the API I'd expect to be able to use the API while one song is playing through the search API

**Actions to reproduce:**

- Issue a search with only one song returning using VLC play from network function.  
(Example: `http://10.228.0.1:1201/get_by_search?title=igel%20im%20nebel&type=song`)
- In a terminal try to list playlists.  
(`curl 'http://10.228.0.1:1201/get_all_playlists?format=text'`)

**Observed behaviour:**

While VLC is buffering the song the `curl` execution blocks and after the song is fully buffered (near its end) the API responds to the `curl` and lists the playlists.

**Expected behaviour:**

VLC continues playing and the `curl` command returns the playlists immediately (plus the duration required to fetch them from the servers of Google).

**Possible fix:**

[Implement concurrency / threading for HTTP requests](http://stackoverflow.com/questions/2398144/python-basehttpserver-httpserver-concurrency-threading)

**Comment by diraimondo** [comment]
This is a known limit of the actual single-thread structure (see README.md). I should switch on something like Twisted. No time at the moment...

**Comment by diraimondo** [comment]
fixed by #58
