### ISSUE TITLE
libffi-dev and libssl-dev not listed as dependencies in the setup, but are required by pip to install the requirements

### ISSUE THREAD

**Issue by BurningMind** [diraimondo/gmusicproxy#54]
These packages should be listed as required in the setup part of the website, as the pip build fails without them.
Running Ubuntu 16.04.

**Comment by diraimondo** [comment]
This should not be a gmusicproxy bug: as you can read from the README.md file, the only distribution-specific packages that I suggest are related to python and to the pip packaging system. Given them, every other build requirement should be managed by pip. 
Could you isolate the python package (among the gmusicproxy pip requirements) that requires these packages?

**Comment by BurningMind** [comment]
The python packages failing to build were cryptography and cffi because they were respectively missing opensslv.h and cffi.h, which are brought by the packages I mentioned in the title.
I am not a regular user of the Python environment nor of the pip tool, but how is pip supposed to install the other build requirements without root privilege? Does that imply that I should have ran pip as sudo?

**Comment by diraimondo** [comment]
You are right about the necessity to manually install the platform-specific dependency. I can specify these possible dependency in the ubuntu specific notes but it has a relative value: they are distribution specific (what about debian, are they the same?) and, maybe, version specific (did they change in 16.04?). The official documentation of 'cryptography' python package suggests other dependencies: https://cryptography.io/en/latest/installation/#building-cryptography-on-linux Can you verify that they imply your needed packages? What about other OSs?
