### ISSUE TITLE
Estimated song size is out by 5 bytes (33>28)

### ISSUE THREAD

**Issue by RobDeBagel** [diraimondo/gmusicproxy#56]
In tests, I'm fining that the estimated song size is out. The current delta in the code is 28, but I'm finding that songs I retrieve are out.

I thought it was fixed at 33, but I've just had a song that's out by 4191.

**Comment by diraimondo** [comment]
It looks that the reported size differs time by time, and song by song. This is an annoying problem. I've asked to @simon-weber, the author of gmusicapi, about this difference but it looks unknown. Could you collect some examples of song with the related sizes? We could investigate the content of them.

**Comment by diraimondo** [comment]
I can't reproduce the problem on my local tests. Feel free to reopen this report but with references to tracks with the specified behavior. Sorry.

**Comment by diraimondo** [comment]
I'm facing the reported problem: Google reports wrong size with different deltas. It is usually 28 bytes (as supported by the actual code) but I'm facing also few songs with a delta of 33 bytes but also some with a completely wrong size...

samples:
- regular 28 bytes delta: `T4wc2oqhcqw6iihmh5xuwek7mua`
- sporadic 33 bytes delta: `Tpnp7mlgyj7lun24qythy72kduy`
- very wrong delta: `Txb4xwg5m736wg6fhgpiakhrij4`

I don't know how to handle this: some songs could be trimmed on the tail. I could disable the reported size (as in the early versions of gmusicproxy) but this would disable the progress bar on many players. I could report an heuristically determined size that is quiet bigger than the reported one: this would allow to see the progress bar (with a non-exact indication) and should prevent many truncations (but I can't be sure...).

Suggestions?

**Comment by simon-weber** [comment]
I'd imagine that Google gives the filesize in the stream response headers. See if you can get access to the `content-length` header after the final redirect.

**Comment by abusenius** [comment]
I have also noticed this problem - my player tries to reconnect if the actual song size is smaller than the reported size, and this results in a connection reset.

I think truncating and extending with zeros is not that a bad idea - the biggest difference I've seen so far is 1101 byte and this is about 25 ms at 320 kbit/s. I'll try this out on my playlist.

**Comment by diraimondo** [comment]
I just implemented the suggestion of @simon-weber: it looks to work with the correct size.

@RobDeBagel @abusenius could you test if it works for you too.

**Comment by abusenius** [comment]
Works perfectly since 1 hour, no connection resets, the reported size is correct, thanks!
