### ISSUE TITLE
Any native app using this library?

### ISSUE THREAD

**Issue by FezVrasta** [diraimondo/gmusicproxy#61]
Is there any Mac native application using this API to provide a native Google Play Music player?

**Comment by diraimondo** [comment]
Sorry, I don't know any native application of Mac that uses gmusicproxy or the underling gmusicapi. It is also true that you can just use any native MPD-client to play gmusicproxy URLs on a local instance of MPD.

**Comment by FezVrasta** [comment]
Thanks for the info.
