### ISSUE TITLE
support gmusicapi > 9.0.0

### ISSUE THREAD

**Issue by bigmittens** [diraimondo/gmusicproxy#67]
setup.py only allows for `gmusicapi==9.0.0`, creating problems for package managers. have versions greater than 9.0.0 been tested yet?

**Comment by diraimondo** [comment]
I'll verify if it is doable this week-end.

**Comment by kmac** [comment]
I seem to have picked up the gmusicapi 10.x from my package manager (on arch) and it's breaking a few things, most notably this one:

* breaking: Mobileclient.search_all_access is now Mobileclient.search
