### ISSUE TITLE
'Mobileclient' object has no attribute 'search'

### ISSUE THREAD

**Issue by alesms** [diraimondo/gmusicproxy#72]
Hi,
I downloaded the last version of Gmusicproxy (1.0.7b1)  but after i launch it, when i try to search an artist, or an album, or radio ecc. i get always this error 'Mobileclient' object has no attribute 'search'
in
File "./GMusicProxy", line 540, in <lambda>
I saw the line in this version and in previous version of gmusicproxy and i found a difference:
in the last version i found this (when i try to search for an artist): 
results = self._robust_retry(lambda: api.search(query_artist))
in previous version i found this (when i try to search for an artist): 
results = self._robust_retry(lambda:api.search_all_access(query_artist))
am i in error with something or it's a bug?

Thanks

**Comment by diraimondo** [comment]
What version of  `gmusicapi` are you using? Now v.10 is required.

**Comment by alesms** [comment]
ok, thank you. I updated gmusicapi and now it work!
Can i ask for another problem that i have in precedent version and also in this version?
a lot of time, e.g. when i search for album or artist ecc i receive this error
Detected remote peer disconnected.
for example, now i search for whish you where here (i mean album) and i receive this error:
Searching for album with query:  wish you were here 
Selected album: Pink Floyd - Wish You Were Here (Bw2kk345y5ivx4m35tflhzsvg6a)
Getting the tracks of the album with id 'Bw2kk345y5ivx4m35tflhzsvg6a': Wish You Were Here - Pink Floyd
Streaming song with id 'Tnw4c5qriugzqsh6nrvb6ofuqwy': Pink Floyd - Shine On You Crazy Diamond, Pts. 1-5 (2011 Remastered Version)
192.168.1.85 - - [18/Dec/2016 12:20:33] "GET /get_song?id=Tnw4c5qriugzqsh6nrvb6ofuqwy HTTP/1.1" 200 -
Detected connection reset.

**Comment by alesms** [comment]
this is a random error but very very frequently and the result is that it don't play a lot of song

**Comment by diraimondo** [comment]
What client are you using? Does it happen also using curl to query or vlc to play? I don't understand if this is a problem of connection between the client (curl, vlc) and gmusicproxy or the latter the Google servers?

**Comment by alesms** [comment]
i use pychromecast to cast the content on chromecast
for example i do this:
cast = pychromecast.get_chromecast(friendly_name="my_chromecast_name")
cast.wait()
mc = cast.media_controller
mc.play_media('http://192.168.1.86:9999/get_song?id=Tnw4c5qriugzqsh6nrvb6ofuqwy', 'audio/mp3')
where
http://192.168.1.86:9999/get_song?id=Tnw4c5qriugzqsh6nrvb6ofuqwy
is a single track extract from the .m3u file created with gmusicproxy

**Comment by diraimondo** [comment]
You should first test gmusicproxy with a standard client to see if these errors persist. I was used to see these errors in gmusicproxy logs only when the client early interrupts the client<->gmp connection. I can't say what the chromecast does...

**Comment by alesms** [comment]
ok thank you, i'll log the pychromecast behaviour

**Comment by diraimondo** [comment]
Ok, open another report if you spot a gmusicproxy fault in supporting your usage scenario.

**Comment by alesms** [comment]
ok, thanks!
