### ISSUE TITLE
Is there a way to get a SHUFFLED playlist?

### ISSUE THREAD

**Issue by mgillespie** [diraimondo/gmusicproxy#77]
For an wifi speaker that understands playlists, but isn't that easy to get into a Shuffle mode, the playlists are currently not much use, as they are the same each time.  Is there a way to shuffle them before presenting them?

If not, and before I start hacking around with my basic python skills, to make this happen for me, is it even feasible? or would there be any forseeable technical barriers?

**Comment by diraimondo** [comment]
There should not be any problem in shuffling the playlists (if a specific parameter is included) on the fly. In my TODO list.

**Comment by diraimondo** [comment]
Could you test the new feature?

**Comment by mgillespie** [comment]
Yep, working fine here.  Awesome job.
