### ISSUE TITLE
Getting thumbs up playlist and shuffling complete song list.

### ISSUE THREAD

**Issue by mgillespie** [diraimondo/gmusicproxy#79]
I rely heavily on my thumbs up playlist (I often hear songs I like, and just give it the thumb up).

I would like a playlist of these songs.  I looked at the current functionality for getting playlists, but it didn't list my thumbsup playlist in there :-(

Anyway, I did some python hacking, and made my own.  I added a optional rating (and shuffle) parameters to  get_collection

I haven't raised a pull request, as 

a) there may already be a way to to get ThumbsUp, it's just it wasn't obvious for me (but it would still be nice to implement the shuffle on entire collection, just like playlists)
b) my python skills are hacky at best, and there is likely a far better way to implement this.

My changes are here:

https://github.com/mgillespie/gmusicproxy/commit/6d72ab1ee6df5bc44311a62f184983f0caadeac6

**Comment by diraimondo** [comment]
It was planned to support the shuffle feature for other kind of lists. Your implementation for `get_collection` looks fine.
For the playlist of the liked songs: I wanted to implement this too but the api (read Google) doesn't report such content (I discussed of this my Simon @simon-weber in the past). What you implemented is a filtering on the collection but you could even liked a song that doesn't belong to it (it is common listening stations). So your idea is a partial solution: but it could work.

Before the PR, could you document the changes in the README.md file?

**Comment by mgillespie** [comment]
Done and PR raised.
