### ISSUE TITLE
GMusicProxy hangs sometimes downloading song

### ISSUE THREAD

**Issue by keschrich** [diraimondo/gmusicproxy#82]
Sometimes when I try to download a song from GMusicProxy, the download just hangs. Sometimes if I try it several times with the same URL it eventually comes through, but it doesn't seem to be always.. 

Debug log attached
[failed.txt](https://github.com/diraimondo/gmusicproxy/files/755553/failed.txt)

**Comment by diraimondo** [comment]
It looks that it hangs on the collection-cache reload. This memory cache is used for the metadata of the uploaded songs (potentially new songs or when you don't subscribe the All Access service).

Few questions to better understand:
- what do you mean for "hangs"? It requires a long time to complete the request or it is definitively blocked?
- when it hangs, is the requested song an uploaded one? 
- how many songs in your personal collection?
- how fast is your Internet connection?

**Comment by keschrich** [comment]
Thanks for the reply @diraimondo .

> what do you mean for "hangs"? It requires a long time to complete the request or it is definitively blocked?

It just sits there indefinitely until another request comes in. I ended up adding a 10 second timeout to my script..

> when it hangs, is the requested song an uploaded one?

No

> how many songs in your personal collection?

None, strictly using AA

> how fast is your Internet connection?

100MBit

**Comment by diraimondo** [comment]
I've found two related bugs:
- a deadlock in cache management;
- the reported song ids should all start with a `T` or should have an uuid-style structure.

Both the problems should be fixed in master: could you test it?

**Comment by keschrich** [comment]
Seems to be working perfectly now! Thanks for the quick response and resolution.

**Comment by diraimondo** [comment]
I'm happy it worked for you!
