### ISSUE TITLE
Bogus id field in URLs returned by /get_by_search with type=matches

### ISSUE THREAD

**Issue by CMB** [diraimondo/gmusicproxy#90]
I'm not really sure whose bug this is.  Perhaps it's GMusicAPI's bug
or a bug in the Google API itself?
With /get_by_search?type=matches, I get back a playlist of songs.
The ids in the URLs should all start with T, but none of them do.
The nid fields of those tracks are apparently missing their initial T.
If it's not GMusicProxy's bug, it's at least easy to fix there, and I'd
be willing to send a PR to do it.

**Comment by diraimondo** [comment]
Could you provide an example query?

**Comment by CMB** [comment]
http://localhost:9999/get_by_search?type=matches&artist=Enya

**Comment by diraimondo** [comment]
Could you check if it is fixed for you?

**Comment by CMB** [comment]
Yes, that fixed it for me.  Thank you!
