### ISSUE TITLE
content-type of playlists?

### ISSUE THREAD

**Issue by CMB** [diraimondo/gmusicproxy#93]
I notice that GMusicProxy sends playlists with
Content-type: audio/mpegurl.  But as far as I can tell, mpd only
recognizes an M3U playlist if it is sent as audio/x-mpegurl.
Well, it can also look at the extension of the URL's path, but not
relevant to this discussion.
So doing things like mpc load http://localhost:9999/get_collection
is out of the question.
I'm not sure if loading playlists directly from GMusicProxy
URLs is a reasonable thing to do, but assuming it is,
who is right about the content type for m3u?  GMusicProxy or mpd?
If it's GMusicProxy, maybe I need to open a bug with mpd
and tell them to update mime types?

**Comment by diraimondo** [comment]
Do you mean that if you use the `Content-type: audio/x-mpegurl` header, you are able to use something like `mpc load http://localhost:9999/get_collection`?

**Comment by CMB** [comment]
> Do you mean that if you use the Content-type: audio/x-mpegurl header, you are able to use something like mpc load
> http://localhost:9999/get_collection?

Exactly.

**Comment by diraimondo** [comment]
Looking around for references about the right content-type for M3U playlists: it looks that both are used. I could even decide to switch to the mpd preferred one but I think it should be the player to manages all possible cases. 

I created a PR on the mpd project to manage such case: https://github.com/MusicPlayerDaemon/MPD/pull/49

**Comment by CMB** [comment]
> Looking around for references about the right content-type for M3U playlists: it looks that both are used.

That's what I suspected, I just wasn't sure whether they were equivalent.

> I created a PR on the mpd project to manage such case: MusicPlayerDaemon/MPD#49

Thank you!

**Comment by diraimondo** [comment]
My PR has been accepted: the change will be in mpd v.0.20.8.
